#!/bin/bash
#SBATCH --job-name=FinchContPred
#SBATCH --time=0-2:00:00
#SBATCH --ntasks=1

### just increase this as necessary
#SBATCH --mem=32g
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --account=mb20
#SBATCH --partition=m3g,m3h

module load pytorch/1.3-cuda10

python deploy.py \
--record_path '/home/mmoh0027/mb20/Finch/OriginalRecordings/' \
--label_path  '/home/mmoh0027/mb20/Finch/LabelledData/'
